"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Event$ = void 0;
var Event$;
(function (Event$) {
    Event$[Event$["UNDEFINED"] = 0] = "UNDEFINED";
    Event$[Event$["INIT"] = 1] = "INIT";
    Event$[Event$["START"] = 2] = "START";
    Event$[Event$["STOP"] = 3] = "STOP";
    Event$[Event$["READY"] = 4] = "READY";
    Event$[Event$["SAVE"] = 5] = "SAVE";
    Event$[Event$["BEFORE_SAVE"] = 6] = "BEFORE_SAVE";
    Event$[Event$["AFTER_SAVE"] = 7] = "AFTER_SAVE";
    Event$[Event$["SAVED"] = 8] = "SAVED";
    Event$[Event$["LOAD"] = 9] = "LOAD";
    Event$[Event$["BEFORE_LOAD"] = 10] = "BEFORE_LOAD";
    Event$[Event$["AFTER_LOAD"] = 11] = "AFTER_LOAD";
    Event$[Event$["LOADED"] = 12] = "LOADED";
    Event$[Event$["PROCESS"] = 13] = "PROCESS";
    Event$[Event$["BEFORE_PROCESS"] = 14] = "BEFORE_PROCESS";
    Event$[Event$["AFTER_PROCESS"] = 15] = "AFTER_PROCESS";
    Event$[Event$["PROCESSED"] = 16] = "PROCESSED";
    Event$[Event$["DESTROY"] = 17] = "DESTROY";
    Event$[Event$["BEFORE_DESTROY"] = 18] = "BEFORE_DESTROY";
    Event$[Event$["AFTER_DESTROY"] = 19] = "AFTER_DESTROY";
    Event$[Event$["DESTROYED"] = 20] = "DESTROYED";
    Event$[Event$["DELETE"] = 21] = "DELETE";
    Event$[Event$["BEFORE_DELETE"] = 22] = "BEFORE_DELETE";
    Event$[Event$["AFTER_DELETE"] = 23] = "AFTER_DELETE";
    Event$[Event$["DELETED"] = 24] = "DELETED";
    Event$[Event$["INSERT"] = 25] = "INSERT";
    Event$[Event$["BEFORE_INSERT"] = 26] = "BEFORE_INSERT";
    Event$[Event$["AFTER_INSERT"] = 27] = "AFTER_INSERT";
    Event$[Event$["INSERTED"] = 28] = "INSERTED";
    Event$[Event$["SET"] = 29] = "SET";
    Event$[Event$["BEFORE_SET"] = 30] = "BEFORE_SET";
    Event$[Event$["AFTER_SET"] = 31] = "AFTER_SET";
    Event$[Event$["INSTALLED"] = 32] = "INSTALLED";
    Event$[Event$["ADD"] = 33] = "ADD";
    Event$[Event$["BEFORE_ADD"] = 34] = "BEFORE_ADD";
    Event$[Event$["AFTER_ADD"] = 35] = "AFTER_ADD";
    Event$[Event$["ADDED"] = 36] = "ADDED";
    Event$[Event$["PUSH"] = 37] = "PUSH";
    Event$[Event$["BEFORE_PUSH"] = 38] = "BEFORE_PUSH";
    Event$[Event$["AFTER_PUSH"] = 39] = "AFTER_PUSH";
    Event$[Event$["PUSHED"] = 40] = "PUSHED";
    Event$[Event$["POP"] = 41] = "POP";
    Event$[Event$["BEFORE_POP"] = 42] = "BEFORE_POP";
    Event$[Event$["AFTER_POP"] = 43] = "AFTER_POP";
    Event$[Event$["DETECT"] = 44] = "DETECT";
    Event$[Event$["BEFORE_DETECT"] = 45] = "BEFORE_DETECT";
    Event$[Event$["AFTER_DETECT"] = 46] = "AFTER_DETECT";
    Event$[Event$["DETECTED"] = 47] = "DETECTED";
    Event$[Event$["PRESS"] = 48] = "PRESS";
    Event$[Event$["BEFORE_PRESS"] = 49] = "BEFORE_PRESS";
    Event$[Event$["AFTER_PRESS"] = 50] = "AFTER_PRESS";
    Event$[Event$["PRESSED"] = 51] = "PRESSED";
})(Event$ = exports.Event$ || (exports.Event$ = {}));
